# Generated by Django 3.2.7 on 2021-09-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_sample_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='surname',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
