# Generated by Django 3.2.7 on 2021-09-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20210927_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='city',
            field=models.TextField(default='Cacak', max_length=255),
        ),
    ]
